# Generated by ChatGPT for ScropIDS bootstrap.

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("hostname", models.CharField(max_length=255)),
                ("operating_system", models.CharField(max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("api_token_hash", models.CharField(blank=True, max_length=64, unique=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("hostname",)},
        ),
        migrations.CreateModel(
            name="LLMProviderConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("openai_compatible", "OpenAI Compatible"), ("ollama", "Ollama")],
                        max_length=32,
                    ),
                ),
                ("base_url", models.URLField(max_length=512)),
                ("model", models.CharField(max_length=120)),
                ("encrypted_api_key", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="SchedulerConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="default", max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("aggregation_interval", models.PositiveIntegerField(default=300)),
                ("llm_mode", models.CharField(choices=[("realtime", "Realtime"), ("batch", "Batch")], default="batch", max_length=16)),
                (
                    "min_severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "alert_threshold",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        default="high",
                        max_length=16,
                    ),
                ),
                ("last_aggregation_run", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scheduler Config",
                "verbose_name_plural": "Scheduler Config",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=128)),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        default="low",
                        max_length=16,
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("source_timestamp", models.DateTimeField()),
                ("processed", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="core.agent")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="AggregatedWindow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("source_event_count", models.PositiveIntegerField(default=0)),
                ("summary_json", models.JSONField()),
                ("analyzed", models.BooleanField(default=False)),
                ("llm_output", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="aggregates", to="core.agent")),
            ],
            options={"ordering": ("-window_end",)},
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "threat_level",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                ("llm_analysis", models.JSONField()),
                ("status", models.CharField(choices=[("open", "Open"), ("in_progress", "In Progress"), ("resolved", "Resolved")], default="open", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="alerts", to="core.agent")),
                (
                    "aggregate",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="alerts", to="core.aggregatedwindow"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["processed", "created_at"], name="core_event_process_17de8d_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["event_type", "severity"], name="core_event_event_t_481f35_idx"),
        ),
        migrations.AddIndex(
            model_name="aggregatedwindow",
            index=models.Index(fields=["analyzed", "created_at"], name="core_aggrega_analyze_a93770_idx"),
        ),
        migrations.AddIndex(
            model_name="aggregatedwindow",
            index=models.Index(fields=["agent", "window_start", "window_end"], name="core_aggrega_agent_i_fa4b73_idx"),
        ),
    ]
